[general]
fullscreen = true
initial-tool = "brush"
annotation-size-factor = 2
copy-command = "wl-copy"
save-after-copy = true
output-filename = "/home/malick-tammal/Pictures/Screenshots/%Y%m%d_%H%M%S.png"
early-exit = true
